 const Users = [
    {
        id:1,
        profilePicture:"/assets/person/img1.jpg",
        username:"Virat Kohli",
    },
    {
        id:2,
        profilePicture:"/assets/person/img2.jpg",
        username:"Christiano Ronaldo",
    },
    {
        id:3,
        profilePicture:"/assets/person/img3.jpg",
        username:"Rohit Sharma",
    },
    {
        id:4,
        profilePicture:"/assets/person/img4.jpg",
        username:"Mahendra Singh Dhoni",
    },
    {
        id:5,
        profilePicture:"/assets/person/img5.jpg",
        username:"Shahrukh Khan",
    },
    {
        id:6,
        profilePicture:"/assets/person/img6.jpg",
        username:"Salmaan Khan",
    },
    {
        id:7,
        profilePicture:"/assets/person/img7.jpg",
        username:"Tom Cruise",
    },
    {
        id:8,
        profilePicture:"/assets/person/img8.jpg",
        username:"Lionel Messi",
    },
    {
        id:9,
        profilePicture:"/assets/person/img9.jpg",
        username:"Narendra Modi",
    },
    {
        id:10,
        profilePicture:"/assets/person/img10.jpg",
        username:"Shreya Ghosal",
    },

];


 const Posts = [
    {
        id:1,
        desc:"Love Nature",
        photo:"/assets/post/1.jpg",
        date:"2 mins ago",
        userId:1,
        like:34,
        comment:1,
    },
    {
        id:2,
        photo:"/assets/post/2.jpg",
        date:"1 hr ago",
        userId:2,
        like:88,
        comment:6,
    },
    {
        id:3,
        photo:"/assets/post/3.jpg",
        date:"54 mins ago",
        userId:3,
        like:45,
        comment:0,
    },
    {
        id:4,
        photo:"/assets/post/4.jpg",
        date:"2 hr ago",
        userId:4,
        like:102,
        comment:12,
    },
    {
        id:5,
        photo:"/assets/post/5.jpg",
        date:"5 mins ago",
        userId:5,
        like:34,
        comment:22,
    },
    {
        id:6,
        photo:"/assets/post/6.jpg",
        date:"1 day ago",
        userId:6,
        like:68,
        comment:10,
    },
    {
        id:7,
        desc:"Training hard for the next match!",
        photo:"/assets/post/7.jpg",
        date:"3 hrs ago",
        userId:1,
        like:156,
        comment:23,
    },
    {
        id:8,
        desc:"Beautiful sunset today",
        photo:"/assets/post/1.jpg",
        date:"6 hrs ago",
        userId:9,
        like:89,
        comment:15,
    },
    {
        id:9,
        desc:"Movie night with friends",
        photo:"/assets/post/2.jpg",
        date:"1 day ago",
        userId:6,
        like:234,
        comment:45,
    },
    {
        id:10,
        desc:"Amazing concert last night!",
        photo:"/assets/post/3.jpg",
        date:"2 days ago",
        userId:5,
        like:178,
        comment:67,
    },
    {
        id:11,
        desc:"New project announcement",
        photo:"/assets/post/4.jpg",
        date:"3 days ago",
        userId:9,
        like:445,
        comment:89,
    },
    {
        id:12,
        desc:"Football practice session",
        photo:"/assets/post/5.jpg",
        date:"4 days ago",
        userId:2,
        like:267,
        comment:34,
    },
]
export  {Users,Posts};
